import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  useColorScheme,
  View,
} from 'react-native';

import {Colors, Header} from 'react-native/Libraries/NewAppScreen';
import Board from './src/components/Board';

function App(): React.JSX.Element {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  // const [puzzle, setPuzzle] = useState(JSON.parse(JSON.stringify(initialPuzzle)))

  const puzzle = [
    {
      id: '1',
      value: 'A1',
      row: 'A',
      column: 1,
      target: true,
      clickType: 'default',
    },
    {
      id: '2',
      value: 'A2',
      row: 'A',
      column: 2,
      target: false,
      clickType: 'default',
    },
    {
      id: '3',
      value: 'A3',
      row: 'A',
      column: 3,
      target: true,
      clickType: 'default',
    },
    {
      id: '4',
      value: 'A4',
      row: 'A',
      column: 4,
      target: true,
      clickType: 'default',
    },
    {
      id: '5',
      value: 'A5',
      row: 'A',
      column: 5,
      target: true,
      clickType: 'default',
    },
    {
      id: '6',
      value: 'A6',
      row: 'A',
      column: 6,
      target: false,
      clickType: 'default',
    },
    {
      id: '7',
      value: 'A7',
      row: 'A',
      column: 7,
      target: true,
      clickType: 'default',
    },
    {
      id: '8',
      value: 'A8',
      row: 'A',
      column: 8,
      target: false,
      clickType: 'default',
    },
    {
      id: '9',
      value: 'B1',
      row: 'B',
      column: 1,
      target: true,
      clickType: 'default',
    },
    {
      id: '10',
      value: 'B2',
      row: 'B',
      column: 2,
      target: false,
      clickType: 'default',
    },
    {
      id: '11',
      value: 'B3',
      row: 'B',
      column: 3,
      target: true,
      clickType: 'default',
    },
    {
      id: '12',
      value: 'B4',
      row: 'B',
      column: 4,
      target: true,
      clickType: 'default',
    },
    {
      id: '13',
      value: 'B5',
      row: 'B',
      column: 5,
      target: true,
      clickType: 'default',
    },
    {
      id: '14',
      value: 'B6',
      row: 'B',
      column: 6,
      target: false,
      clickType: 'default',
    },
    {
      id: '15',
      value: 'B7',
      row: 'B',
      column: 7,
      target: true,
      clickType: 'default',
    },
    {
      id: '16',
      value: 'B8',
      row: 'B',
      column: 8,
      target: false,
      clickType: 'default',
    },
    {
      id: '17',
      value: 'C1',
      row: 'C',
      column: 1,
      target: true,
      clickType: 'default',
    },
    {
      id: '18',
      value: 'C2',
      row: 'C',
      column: 2,
      target: false,
      clickType: 'default',
    },
    {
      id: '19',
      value: 'C3',
      row: 'C',
      column: 3,
      target: true,
      clickType: 'default',
    },
    {
      id: '20',
      value: 'C4',
      row: 'C',
      column: 4,
      target: true,
      clickType: 'default',
    },
    {
      id: '21',
      value: 'C5',
      row: 'C',
      column: 5,
      target: true,
      clickType: 'default',
    },
    {
      id: '22',
      value: 'C6',
      row: 'C',
      column: 6,
      target: false,
      clickType: 'default',
    },
    {
      id: '23',
      value: 'C7',
      row: 'C',
      column: 7,
      target: true,
      clickType: 'default',
    },
    {
      id: '24',
      value: 'C8',
      row: 'C',
      column: 8,
      target: false,
      clickType: 'default',
    },
    {
      id: '25',
      value: 'D1',
      row: 'D',
      column: 1,
      target: true,
      clickType: 'default',
    },
    {
      id: '26',
      value: 'D2',
      row: 'D',
      column: 2,
      target: false,
      clickType: 'default',
    },
    {
      id: '27',
      value: 'D3',
      row: 'D',
      column: 3,
      target: true,
      clickType: 'default',
    },
    {
      id: '28',
      value: 'D4',
      row: 'D',
      column: 4,
      target: true,
      clickType: 'default',
    },
    {
      id: '29',
      value: 'D5',
      row: 'D',
      column: 5,
      target: true,
      clickType: 'default',
    },
    {
      id: '30',
      value: 'D6',
      row: 'D',
      column: 6,
      target: false,
      clickType: 'default',
    },
    {
      id: '31',
      value: 'D7',
      row: 'D',
      column: 7,
      target: true,
      clickType: 'default',
    },
    {
      id: '32',
      value: 'D8',
      row: 'D',
      column: 8,
      target: false,
      clickType: 'default',
    },
    {
      id: '33',
      value: 'E1',
      row: 'E',
      column: 1,
      target: true,
      clickType: 'default',
    },
    {
      id: '34',
      value: 'E2',
      row: 'E',
      column: 2,
      target: false,
      clickType: 'default',
    },
    {
      id: '35',
      value: 'E3',
      row: 'E',
      column: 3,
      target: true,
      clickType: 'default',
    },
    {
      id: '36',
      value: 'E4',
      row: 'E',
      column: 4,
      target: true,
      clickType: 'default',
    },
    {
      id: '37',
      value: 'E5',
      row: 'E',
      column: 5,
      target: true,
      clickType: 'default',
    },
    {
      id: '38',
      value: 'E6',
      row: 'E',
      column: 6,
      target: false,
      clickType: 'default',
    },
    {
      id: '39',
      value: 'E7',
      row: 'E',
      column: 7,
      target: true,
      clickType: 'default',
    },
    {
      id: '40',
      value: 'E8',
      row: 'E',
      column: 8,
      target: false,
      clickType: 'default',
    },
    {
      id: '41',
      value: 'F1',
      row: 'F',
      column: 1,
      target: true,
      clickType: 'default',
    },
    {
      id: '42',
      value: 'F2',
      row: 'F',
      column: 2,
      target: false,
      clickType: 'default',
    },
    {
      id: '43',
      value: 'F3',
      row: 'F',
      column: 3,
      target: true,
      clickType: 'default',
    },
    {
      id: '44',
      value: 'F4',
      row: 'F',
      column: 4,
      target: true,
      clickType: 'default',
    },
    {
      id: '45',
      value: 'F5',
      row: 'F',
      column: 5,
      target: true,
      clickType: 'default',
    },
    {
      id: '46',
      value: 'F6',
      row: 'F',
      column: 6,
      target: false,
      clickType: 'default',
    },
    {
      id: '47',
      value: 'F7',
      row: 'F',
      column: 7,
      target: true,
      clickType: 'default',
    },
    {
      id: '48',
      value: 'F8',
      row: 'F',
      column: 8,
      target: false,
      clickType: 'default',
    },
    {
      id: '49',
      value: 'G1',
      row: 'G',
      column: 1,
      target: true,
      clickType: 'default',
    },
    {
      id: '50',
      value: 'G2',
      row: 'G',
      column: 2,
      target: false,
      clickType: 'default',
    },
    {
      id: '51',
      value: 'G3',
      row: 'G',
      column: 3,
      target: true,
      clickType: 'default',
    },
    {
      id: '52',
      value: 'G4',
      row: 'G',
      column: 4,
      target: true,
      clickType: 'default',
    },
    {
      id: '53',
      value: 'G5',
      row: 'G',
      column: 5,
      target: true,
      clickType: 'default',
    },
    {
      id: '54',
      value: 'G6',
      row: 'G',
      column: 6,
      target: false,
      clickType: 'default',
    },
    {
      id: '55',
      value: 'G7',
      row: 'G',
      column: 7,
      target: true,
      clickType: 'default',
    },
    {
      id: '56',
      value: 'G8',
      row: 'G',
      column: 8,
      target: false,
      clickType: 'default',
    },
    {
      id: '57',
      value: 'H1',
      row: 'H',
      column: 1,
      target: true,
      clickType: 'default',
    },
    {
      id: '58',
      value: 'H2',
      row: 'H',
      column: 2,
      target: false,
      clickType: 'default',
    },
    {
      id: '59',
      value: 'H3',
      row: 'H',
      column: 3,
      target: true,
      clickType: 'default',
    },
    {
      id: '60',
      value: 'H4',
      row: 'H',
      column: 4,
      target: true,
      clickType: 'default',
    },
    {
      id: '61',
      value: 'H5',
      row: 'H',
      column: 5,
      target: true,
      clickType: 'default',
    },
    {
      id: '62',
      value: 'H6',
      row: 'H',
      column: 6,
      target: false,
      clickType: 'default',
    },
    {
      id: '63',
      value: 'H7',
      row: 'H',
      column: 7,
      target: true,
      clickType: 'default',
    },
    {
      id: '64',
      value: 'H8',
      row: 'H',
      column: 8,
      target: false,
      clickType: 'default',
    },
  ];

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar
        barStyle={isDarkMode ? 'light-content' : 'dark-content'}
        backgroundColor={backgroundStyle.backgroundColor}
      />
      <View style={backgroundStyle}>
        <Header />
        <View
          style={{
            backgroundColor: isDarkMode ? Colors.black : Colors.white,
          }}>
          <Board puzzle={puzzle} />
        </View>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({});

export default App;
