export const B2game1 = [
  {
    id: '1',
    value: 'A1',
    row: 1,
    column: 1,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '',
},
  {
    id: '2',
    value: 'A2',
    row: 1,
    column: 2,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '1',
},
  {
    id: '3',
    value: 'A3',
    row: 1,
    column: 3,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '2',
},
  {
    id: '4',
    value: 'A4',
    row: 1,
    column: 4,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '3',
},
  {
    id: '5',
    value: 'A5',
    row: 1,
    column: 5,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '4',
},
  {
    id: '6',
    value: 'A6',
    row: 1,
    column: 6,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '5',
},
  {
    id: '7',
    value: 'A7',
    row: 1,
    column: 7,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '6',
},
  {
    id: '8',
    value: 'A8',
    row: 1,
    column: 8,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '7',
},
  {
    id: '9',
    value: 'A9',
    row: 1,
    column: 9,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '8',
},
  {
    id: '10',
    value: 'A10',
    row: 1,
    column: 10,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '9',
},
  {
    id: '11',
    value: 'A11',
    row: 1,
    column: 11,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '10',
},
  {
    id: '12',
    value: 'B1',
    row: 2,
    column: 1,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '1',
},
  {
    id: '13',
    value: 'B2',
    row: 2,
    column: 2,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '14',
    value: 'B3',
    row: 2,
    column: 3,
    target: true,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '15',
    value: 'B4',
    row: 2,
    column: 4,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '16',
    value: 'B5',
    row: 2,
    column: 5,
    target: true,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '17',
    value: 'B6',
    row: 2,
    column: 6,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '18',
    value: 'B7',
    row: 2,
    column: 7,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '19',
    value: 'B8',
    row: 2,
    column: 8,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '20',
    value: 'B9',
    row: 2,
    column: 9,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '21',
    value: 'B10',
    row: 2,
    column: 10,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '22',
    value: 'B11',
    row: 2,
    column: 11,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '23',
    value: 'C1',
    row: 3,
    column: 1,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '2',
},
  {
    id: '24',
    value: 'C2',
    row: 3,
    column: 2,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '25',
    value: 'C3',
    row: 3,
    column: 3,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '26',
    value: 'C4',
    row: 3,
    column: 4,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '27',
    value: 'C5',
    row: 3,
    column: 5,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '28',
    value: 'C6',
    row: 3,
    column: 6,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '29',
    value: 'C7',
    row: 3,
    column: 7,
    target: true,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '30',
    value: 'C8',
    row: 3,
    column: 8,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '31',
    value: 'C9',
    row: 3,
    column: 9,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '32',
    value: 'C10',
    row: 3,
    column: 10,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '33',
    value: 'C11',
    row: 3,
    column: 11,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '34',
    value: 'D1',
    row: 4,
    column: 1,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '3',
},
  {
    id: '35',
    value: 'D2',
    row: 4,
    column: 2,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '36',
    value: 'D3',
    row: 4,
    column: 3,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '37',
    value: 'D4',
    row: 4,
    column: 4,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '38',
    value: 'D5',
    row: 4,
    column: 5,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '39',
    value: 'D6',
    row: 4,
    column: 6,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '40',
    value: 'D7',
    row: 4,
    column: 7,
    target: true,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '41',
    value: 'D8',
    row: 4,
    column: 8,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '42',
    value: 'D9',
    row: 4,
    column: 9,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '43',
    value: 'D10',
    row: 4,
    column: 10,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '44',
    value: 'D11',
    row: 4,
    column: 11,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '45',
    value: 'E1',
    row: 5,
    column: 1,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '4',
},
  {
    id: '46',
    value: 'E2',
    row: 5,
    column: 2,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '47',
    value: 'E3',
    row: 5,
    column: 3,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '48',
    value: 'E4',
    row: 5,
    column: 4,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '49',
    value: 'E5',
    row: 5,
    column: 5,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '50',
    value: 'E6',
    row: 5,
    column: 6,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '51',
    value: 'E7',
    row: 5,
    column: 7,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '52',
    value: 'E8',
    row: 5,
    column: 8,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '53',
    value: 'E9',
    row: 5,
    column: 9,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '54',
    value: 'E10',
    row: 5,
    column: 10,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '55',
    value: 'E11',
    row: 5,
    column: 11,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '56',
    value: 'F1',
    row: 6,
    column: 1,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '5',
},
  {
    id: '57',
    value: 'F2',
    row: 6,
    column: 2,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '58',
    value: 'F3',
    row: 6,
    column: 3,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '59',
    value: 'F4',
    row: 6,
    column: 4,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '60',
    value: 'F5',
    row: 6,
    column: 5,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '61',
    value: 'F6',
    row: 6,
    column: 6,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '62',
    value: 'F7',
    row: 6,
    column: 7,
    target: true,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '63',
    value: 'F8',
    row: 6,
    column: 8,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '64',
    value: 'F9',
    row: 6,
    column: 9,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '65',
    value: 'F10',
    row: 6,
    column: 10,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '66',
    value: 'F11',
    row: 6,
    column: 11,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '67',
    value: 'G1',
    row: 7,
    column: 1,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '6',
},
  {
    id: '68',
    value: 'G2',
    row: 7,
    column: 2,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '69',
    value: 'G3',
    row: 7,
    column: 3,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '70',
    value: 'G4',
    row: 7,
    column: 4,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '71',
    value: 'G5',
    row: 7,
    column: 5,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '72',
    value: 'G6',
    row: 7,
    column: 6,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '73',
    value: 'G7',
    row: 7,
    column: 7,
    target: true,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '74',
    value: 'G8',
    row: 7,
    column: 8,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '75',
    value: 'G9',
    row: 7,
    column: 9,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '76',
    value: 'G10',
    row: 7,
    column: 10,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '77',
    value: 'G11',
    row: 7,
    column: 11,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '78',
    value: 'H1',
    row: 8,
    column: 1,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '7',
},
  {
    id: '79',
    value: 'H2',
    row: 8,
    column: 2,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '80',
    value: 'H3',
    row: 8,
    column: 3,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '81',
    value: 'H4',
    row: 8,
    column: 4,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '82',
    value: 'H5',
    row: 8,
    column: 5,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '83',
    value: 'H6',
    row: 8,
    column: 6,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '84',
    value: 'H7',
    row: 8,
    column: 7,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '85',
    value: 'H8',
    row: 8,
    column: 8,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '86',
    value: 'H9',
    row: 8,
    column: 9,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '87',
    value: 'H10',
    row: 8,
    column: 10,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '88',
    value: 'H11',
    row: 8,
    column: 11,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '89',
    value: 'I1',
    row: 9,
    column: 1,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '8',
},
  {
    id: '90',
    value: 'I2',
    row: 9,
    column: 2,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '91',
    value: 'I3',
    row: 9,
    column: 3,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '92',
    value: 'I4',
    row: 9,
    column: 4,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '93',
    value: 'I5',
    row: 9,
    column: 5,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '94',
    value: 'I6',
    row: 9,
    column: 6,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '95',
    value: 'I7',
    row: 9,
    column: 7,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '96',
    value: 'I8',
    row: 9,
    column: 8,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '97',
    value: 'I9',
    row: 9,
    column: 9,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '98',
    value: 'I10',
    row: 9,
    column: 10,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '99',
    value: 'I11',
    row: 9,
    column: 11,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '100',
    value: 'J1',
    row: 10,
    column: 1,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '9',
},
  {
    id: '101',
    value: 'J2',
    row: 10,
    column: 2,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '102',
    value: 'J3',
    row: 10,
    column: 3,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '103',
    value: 'J4',
    row: 10,
    column: 4,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '104',
    value: 'J5',
    row: 10,
    column: 5,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '105',
    value: 'J6',
    row: 10,
    column: 6,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '106',
    value: 'J7',
    row: 10,
    column: 7,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '107',
    value: 'J8',
    row: 10,
    column: 8,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '108',
    value: 'J9',
    row: 10,
    column: 9,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '109',
    value: 'J10',
    row: 10,
    column: 10,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '110',
    value: 'J11',
    row: 10,
    column: 11,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '111',
    value: 'K1',
    row: 11,
    column: 1,
    target: false,
    clickType: 'label',
    isLabel: true,
    label: '10',
},
{
  id: '112',
  value: 'K2',
  row: 11,
  column: 2,
  target: false,
  clickType: 'default',
  isLabel: false,
  label: null,
},
{
  id: '113',
  value: 'K3',
  row: 11,
  column: 3,
  target: false,
  clickType: 'default',
  isLabel: false,
  label: null,
},
{
  id: '114',
  value: 'K4',
  row: 11,
  column: 4,
  target: false,
  clickType: 'default',
  isLabel: false,
  label: null,
},
{
  id: '115',
  value: 'K5',
  row: 11,
  column: 5,
  target: false,
  clickType: 'default',
  isLabel: false,
  label: null,
},
{
  id: '116',
  value: 'K6',
  row: 11,
  column: 6,
  target: false,
  clickType: 'default',
  isLabel: false,
  label: null,
},
{
  id: '117',
  value: 'K7',
  row: 11,
  column: 7,
  target: false,
  clickType: 'default',
  isLabel: false,
  label: null,
},
{
  id: '118',
  value: 'K8',
  row: 11,
  column: 8,
  target: false,
  clickType: 'default',
  isLabel: false,
  label: null,
},
{
  id: '119',
  value: 'K9',
  row: 11,
  column: 9,
  target: false,
  clickType: 'default',
  isLabel: false,
  label: null,
},
{
  id: '120',
  value: 'K10',
  row: 11,
  column: 10,
  target: true,
  clickType: 'default',
  isLabel: false,
  label: null,
},
{
  id: '121',
  value: 'K11',
  row: 11,
  column: 11,
  target: true,
  clickType: 'default',
  isLabel: false,
  label: null,
},
];