export const B3game1 = [
  {
    id: '1',
    value: 'A1',
    row: 1,
    column: 1,
    target: false,
    clickType: 'draft/final',
    isLabel: false,
    label: null,
},
  {
    id: '2',
    value: 'A2',
    row: 1,
    column: 2,
    target: false,
    clickType: 'label',
    isLabel: false,
    label: null,
},
  {
    id: '3',
    value: 'A3',
    row: 1,
    column: 3,
    target: false,
    clickType: 'label',
    isLabel: false,
    label: 4,
},
  {
    id: '4',
    value: 'A4',
    row: 1,
    column: 4,
    target: false,
    clickType: 'label',
    isLabel: false,
    label: '7',
},
  {
    id: '5',
    value: 'A5',
    row: 1,
    column: 5,
    target: false,
    clickType: 'label',
    isLabel: false,
    label: null,
},
  {
    id: '6',
    value: 'A6',
    row: 1,
    column: 6,
    target: false,
    clickType: 'label',
    isLabel: false,
    label: '3',
},
  {
    id: '7',
    value: 'A7',
    row: 1,
    column: 7,
    target: false,
    clickType: 'label',
    isLabel: false,
    label: '6',
},
  {
    id: '8',
    value: 'A8',
    row: 1,
    column: 8,
    target: false,
    clickType: 'label',
    isLabel: false,
    label: null,
},
  {
    id: '9',
    value: 'A9',
    row: 1,
    column: 9,
    target: false,
    clickType: 'label',
    isLabel: false,
    label: null,
},
  {
    id: '10',
    value: 'A10',
    row: 1,
    column: 10,
    target: false,
    clickType: 'label',
    isLabel: false,
    label: null,
},
  {
    id: '11',
    value: 'A11',
    row: 1,
    column: 11,
    target: false,
    clickType: 'label',
    isLabel: false,
    label: null,
},
  {
    id: '12',
    value: 'B1',
    row: 2,
    column: 1,
    target: false,
    clickType: 'label',
    isLabel: false,
    label: null,
},
  {
    id: '13',
    value: 'B2',
    row: 2,
    column: 2,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '14',
    value: 'B3',
    row: 2,
    column: 3,
    target: true,
    clickType: 'default',
    isLabel: false,
    label: '2',
},
  {
    id: '15',
    value: 'B4',
    row: 2,
    column: 4,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '16',
    value: 'B5',
    row: 2,
    column: 5,
    target: true,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '17',
    value: 'B6',
    row: 2,
    column: 6,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '18',
    value: 'B7',
    row: 2,
    column: 7,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '19',
    value: 'B8',
    row: 2,
    column: 8,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 1,
},
  {
    id: '20',
    value: 'B9',
    row: 2,
    column: 9,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '21',
    value: 'B10',
    row: 2,
    column: 10,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 3,
},
  {
    id: '22',
    value: 'B11',
    row: 2,
    column: 11,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 6,
},
  {
    id: '23',
    value: 'C1',
    row: 3,
    column: 1,
    target: false,
    clickType: 'label',
    isLabel: false,
    label: null,
},
  {
    id: '24',
    value: 'C2',
    row: 3,
    column: 2,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 5,
},
  {
    id: '25',
    value: 'C3',
    row: 3,
    column: 3,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 2,
},
  {
    id: '26',
    value: 'C4',
    row: 3,
    column: 4,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '27',
    value: 'C5',
    row: 3,
    column: 5,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 7,
},
  {
    id: '28',
    value: 'C6',
    row: 3,
    column: 6,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 2,
},
  {
    id: '29',
    value: 'C7',
    row: 3,
    column: 7,
    target: true,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '30',
    value: 'C8',
    row: 3,
    column: 8,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 5,
},
  {
    id: '31',
    value: 'C9',
    row: 3,
    column: 9,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '32',
    value: 'C10',
    row: 3,
    column: 10,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '33',
    value: 'C11',
    row: 3,
    column: 11,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '34',
    value: 'D1',
    row: 4,
    column: 1,
    target: false,
    clickType: 'label',
    isLabel: false,
    label: 9,
},
  {
    id: '35',
    value: 'D2',
    row: 4,
    column: 2,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '36',
    value: 'D3',
    row: 4,
    column: 3,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 4,
},
  {
    id: '37',
    value: 'D4',
    row: 4,
    column: 4,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '38',
    value: 'D5',
    row: 4,
    column: 5,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 9,
},
  {
    id: '39',
    value: 'D6',
    row: 4,
    column: 6,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '40',
    value: 'D7',
    row: 4,
    column: 7,
    target: true,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '41',
    value: 'D8',
    row: 4,
    column: 8,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '42',
    value: 'D9',
    row: 4,
    column: 9,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '43',
    value: 'D10',
    row: 4,
    column: 10,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '44',
    value: 'D11',
    row: 4,
    column: 11,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 2,
},
  {
    id: '45',
    value: 'E1',
    row: 5,
    column: 1,
    target: false,
    clickType: 'label',
    isLabel: false,
    label: null,
},
  {
    id: '46',
    value: 'E2',
    row: 5,
    column: 2,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 8,
},
  {
    id: '47',
    value: 'E3',
    row: 5,
    column: 3,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '48',
    value: 'E4',
    row: 5,
    column: 4,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 7,
},
  {
    id: '49',
    value: 'E5',
    row: 5,
    column: 5,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '50',
    value: 'E6',
    row: 5,
    column: 6,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '51',
    value: 'E7',
    row: 5,
    column: 7,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '52',
    value: 'E8',
    row: 5,
    column: 8,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 3,
},
  {
    id: '53',
    value: 'E9',
    row: 5,
    column: 9,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '54',
    value: 'E10',
    row: 5,
    column: 10,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 1,
},
  {
    id: '55',
    value: 'E11',
    row: 5,
    column: 11,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 3,
},
  {
    id: '56',
    value: 'F1',
    row: 6,
    column: 1,
    target: false,
    clickType: 'label',
    isLabel: false,
    label: null,
},
  {
    id: '57',
    value: 'F2',
    row: 6,
    column: 2,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 9,
},
  {
    id: '58',
    value: 'F3',
    row: 6,
    column: 3,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 4,
},
  {
    id: '59',
    value: 'F4',
    row: 6,
    column: 4,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '60',
    value: 'F5',
    row: 6,
    column: 5,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 2,
},
  {
    id: '61',
    value: 'F6',
    row: 6,
    column: 6,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 5,
},
  {
    id: '62',
    value: 'F7',
    row: 6,
    column: 7,
    target: true,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '63',
    value: 'F8',
    row: 6,
    column: 8,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 8,
},
  {
    id: '64',
    value: 'F9',
    row: 6,
    column: 9,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '65',
    value: 'F10',
    row: 6,
    column: 10,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '66',
    value: 'F11',
    row: 6,
    column: 11,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '67',
    value: 'G1',
    row: 7,
    column: 1,
    target: false,
    clickType: 'label',
    isLabel: false,
    label: null,
},
  {
    id: '68',
    value: 'G2',
    row: 7,
    column: 2,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 7,
},
  {
    id: '69',
    value: 'G3',
    row: 7,
    column: 3,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '70',
    value: 'G4',
    row: 7,
    column: 4,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '71',
    value: 'G5',
    row: 7,
    column: 5,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '72',
    value: 'G6',
    row: 7,
    column: 6,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '73',
    value: 'G7',
    row: 7,
    column: 7,
    target: true,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '74',
    value: 'G8',
    row: 7,
    column: 8,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '75',
    value: 'G9',
    row: 7,
    column: 9,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 8,
},
  {
    id: '76',
    value: 'G10',
    row: 7,
    column: 10,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 3,
},
  {
    id: '77',
    value: 'G11',
    row: 7,
    column: 11,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '78',
    value: 'H1',
    row: 8,
    column: 1,
    target: false,
    clickType: 'label',
    isLabel: false,
    label: 1,
},
  {
    id: '79',
    value: 'H2',
    row: 8,
    column: 2,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: 7,
},
  {
    id: '80',
    value: 'H3',
    row: 8,
    column: 3,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
},
  {
    id: '81',
    value: 'H4',
    row: 8,
    column: 4,
    target: false,
    clickType: 'default',
    isLabel: false,
    label: null,
}];
